<?php

class Location extends CActiveRecord
{

    /**
     * @return string the associated database table name
     */
    public function tableName()
    {
        return 'locations';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules()
    {
        // NOTE: you should only define rules for those attributes that
        // will receive user inputs.
        return array(
            array('name', 'required'),
            array('city', 'required'),
            array('district', 'required'),
            ['id, name, city, district, user_id', 'safe', 'on'=>'search'],

        );
    }

    /**
     * @return array relational rules.
     */
    public function relations()
    {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        return array(
            "user" => [self::BELONGS_TO,"User","user_id"]
        );
    }

    protected function beforeSave()
    {
        $this->user_id = Yii::app()->user->getState("id");
        return parent::beforeSave(); // TODO: Change the autogenerated stub
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels()
    {
        return array(
            'username' => 'Username',
            'password' => 'Password',
            'login' => 'Login',
        );
    }


    /**
     * Returns the static model of the specified AR class.
     * Please note that you should have this exact method in all your CActiveRecord descendants!
     * @param string $className active record class name.
     * @return User the static model class
     */
    public static function model($className=__CLASS__)
    {
        return parent::model($className);
    }



    public function login()
    {
        if($this->_identity===null)
        {
            $this->_identity = new UserIdentity($this->username,$this->password);
            $this->_identity->authenticate();
        }

        if($this->_identity->errorCode === UserIdentity::ERROR_NONE)
        {
            Yii::app()->user->login($this->_identity,3600*24*30);
            return true;
        }
        else
            return false;
    }

    public function register($data)
    {
        return Yii::app()->db->createCommand()->insert("users",[
            "username" => $data["username"],
            "email" => $data["email"],
            "password" => $data["password"],
        ]);
    }
}